### ISSUE TITLE
Mejorar la visualización de errores

### ISSUE THREAD

**Issue by matuu** [PyAr/cooperython#5]
Cuando ocurren excepciones no se visualiza bien el error y el traceback. Buscar alternativas para visualizarlo correctamente

**Comment by hugoruscitti** [comment]
Creo que se veían mal porque estaban mostrándose como párrafos (con el elemento `p` de html), que omite los saltos de lineas y las identaciones.

Cambié el código para que genere elementos tipo `pre`. Avisame si te referías a este problema porfa y re-abrimos el issue.
